export type {
    ApiEnvelope,
    ApiErrorDetail,
    ApiFailure,
    ApiSuccess,
    MoodType,
    AvatarStateType,
    AvatarMode,
    AuthUserDto,
    AuthSessionDto,
    HealthEntryDto,
    MoodEntryDto,
    DailyLogSaveDto,
    StreakDataDto,
    SeedDemoResultDto,
    ClearSeedDemoResultDto,
    AvatarStatusDto,
    AvatarStateDto,
    AvatarLibraryDto,
    FutureState,
    FutureInsightDto,
    AiWeeklyAnalysisDto,
} from '../../server/src/contracts/api';
